# Generated by Django 4.2.27 on 2026-01-22 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Всего пользователей')),
                ('total_events', models.PositiveIntegerField(default=0, verbose_name='Всего событий')),
                ('daily_new_users', models.PositiveIntegerField(default=0, verbose_name='Новых пользователей за день')),
                ('daily_active_users', models.PositiveIntegerField(default=0, verbose_name='Активных пользователей за день')),
                ('daily_created_events', models.PositiveIntegerField(default=0, verbose_name='Созданных событий за день')),
                ('daily_updated_events', models.PositiveIntegerField(default=0, verbose_name='Обновленных событий за день')),
                ('daily_deleted_events', models.PositiveIntegerField(default=0, verbose_name='Удаленных событий за день')),
                ('daily_start_commands', models.PositiveIntegerField(default=0, verbose_name='Команд /start за день')),
                ('daily_help_commands', models.PositiveIntegerField(default=0, verbose_name='Команд /help за день')),
                ('daily_list_commands', models.PositiveIntegerField(default=0, verbose_name='Команд /list за день')),
                ('daily_today_commands', models.PositiveIntegerField(default=0, verbose_name='Команд /today за день')),
                ('daily_stats_commands', models.PositiveIntegerField(default=0, verbose_name='Команд /stats за день')),
                ('user_activity_data', models.JSONField(default=dict, verbose_name='Данные активности пользователей')),
                ('event_type_data', models.JSONField(default=dict, verbose_name='Данные по типам событий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='Новые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='calendar_app.calendarevent', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_changes', to='calendar_app.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог изменения события',
                'verbose_name_plural': 'Логи изменений событий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, verbose_name='Команда')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время взаимодействия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='calendar_app.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие пользователя',
                'verbose_name_plural': 'Взаимодействия пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'command'], name='calendar_ap_user_id_d9845c_idx'), models.Index(fields=['created_at'], name='calendar_ap_created_d592ee_idx')],
            },
        ),
    ]
