# Generated by Django 4.2.27 on 2026-01-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_botstatistics_eventchangelog_userinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название встречи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата встречи')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('declined', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to='calendar_app.telegramuser', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('declined', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус участия')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Приглашен')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответил')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='calendar_app.meeting', verbose_name='Встреча')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to='calendar_app.telegramuser', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник встречи',
                'verbose_name_plural': 'Участники встреч',
                'ordering': ['-invited_at'],
                'unique_together': {('meeting', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='MeetingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invitation', 'Приглашение на встречу'), ('confirmation', 'Подтверждение встречи'), ('cancellation', 'Отмена встречи'), ('reminder', 'Напоминание о встрече'), ('update', 'Обновление встречи')], max_length=20, verbose_name='Тип уведомления')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendar_app.meeting', verbose_name='Встреча')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notifications', to='calendar_app.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление о встрече',
                'verbose_name_plural': 'Уведомления о встречах',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', through='calendar_app.MeetingParticipant', to='calendar_app.telegramuser', verbose_name='Участники'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'status'], name='calendar_ap_date_7d5e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer', 'status'], name='calendar_ap_organiz_3a18b9_idx'),
        ),
    ]
