# Generated by Django 4.2.27 on 2026-01-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_meeting_meetingparticipant_meetingnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Доступно ли событие другим пользователям', verbose_name='Публичное событие'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['is_public'], name='calendar_ap_is_publ_775178_idx'),
        ),
    ]
